"""Update Equipo table

Revision ID: 308425a07b53
Revises: af48018b6022
Create Date: 2024-03-17 15:31:04.952428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308425a07b53'
down_revision = 'af48018b6022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_index('ix_equipo_nombre')
        batch_op.create_index(batch_op.f('ix_equipo_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipo_nombre'))
        batch_op.create_index('ix_equipo_nombre', ['nombre'], unique=True)

    # ### end Alembic commands ###
