"""Initial commit

Revision ID: fc920322c27f
Revises: 
Create Date: 2024-04-09 22:09:21.761812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc920322c27f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipo_nombre'), ['nombre'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('universidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('participante_seleccionado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('correo_institucional', sa.String(length=128), nullable=False),
    sa.Column('tipo_inscripcion', sa.String(length=64), nullable=False),
    sa.Column('universidad_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_institucional')
    )
    op.create_table('participante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('eps', sa.String(length=128), nullable=False),
    sa.Column('contacto_emergencia', sa.String(length=128), nullable=False),
    sa.Column('parentesco_contacto_emergencia', sa.String(length=128), nullable=False),
    sa.Column('alergias', sa.String(length=255), nullable=False),
    sa.Column('enfermedades', sa.String(length=255), nullable=False),
    sa.Column('numero_contacto_emergencia', sa.String(length=128), nullable=False),
    sa.Column('tratamiento_datos', sa.Boolean(), nullable=False),
    sa.Column('seguridad_asistencia', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id_participante_seleccionado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_participante_seleccionado'], ['participante_seleccionado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participante_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participante_timestamp'))

    op.drop_table('participante')
    op.drop_table('participante_seleccionado')
    op.drop_table('universidad')
    op.drop_table('role')
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipo_nombre'))

    op.drop_table('equipo')
    # ### end Alembic commands ###
